[package]
name = "wave_jumper"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
embedded-graphics = "0.8.1"
rand = "0.9.2"
rodio = "0.21.1"
rpi-pal = {version = "0.22.2", features = ["hal"]}
ssd1306 = "0.10.0"
